apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: pdf-genie
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-storage
  namespace: pdf-genie
spec:
  selector:
    app: qdrant-storage
  ports:
    - port: 6333
      targetPort: 6333
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pdf-genie
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: pdf-genie
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
