apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant-storage
  namespace: pdf-genie
spec:
  serviceName: qdrant-storage
  replicas: 1
  selector:
    matchLabels:
      app: qdrant-storage
  template:
    metadata:
      labels:
        app: qdrant-storage
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrant-data
              mountPath: /qdrant/storage
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"
  volumeClaimTemplates:
    - metadata:
        name: qdrant-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
